### PR TITLE
added support for ESP32 POE ISO manufactured by Olimex. DevBranch

### PR DESCRIPTION
**Pull request by chris-kuhr**

### CODE REVIEW

**Comment by Romkabouter** [comment]
Thanks!

**Comment by chris-kuhr** [comment]
you're welcome

**Comment by Romkabouter** [comment]
Hi @chris-kuhr , I have pushed some changes to the development branch.

- Add support for ETH for all devices
- Added a new Esp32-poe-iso device, which is basically Inmp441Max98357a but with the led code removed since you mentioned that the device has no LED's

Can you check if the device still works?

**Comment by chris-kuhr** [comment]
Hi @Romkabouter,

tested it and works so far. I did not find the time to make it work with Rhasspy though...

**Comment by Romkabouter** [comment]
This is the Rhasspy community: https://community.rhasspy.org/

**Pull request merged**
